"use client";

import { useEffect, useRef } from "react";
import { Mesh, Program, Renderer, Triangle } from "ogl";

type Props = { className?: string; colors?: string[]; speed?: number; scale?: number; turbulence?: number; fluidity?: number; rimWidth?: number; sharpness?: number; shimmer?: number; glow?: number; flowDirection?: "up" | "down" | "left" | "right"; opacity?: number; mouseInteraction?: boolean; mouseStrength?: number; mouseRadius?: number; mouseDampening?: number };
const rgb = (hex: string) => { const value = hex.replace("#", "").padEnd(6, "0"); return [0, 2, 4].map((i) => Number.parseInt(value.slice(i, i + 2), 16) / 255); };
const direction = (value: Props["flowDirection"]) => value === "up" ? [0, 1] : value === "left" ? [-1, 0] : value === "right" ? [1, 0] : [0, -1];

const vertex = `attribute vec2 position; attribute vec2 uv; varying vec2 vUv; void main(){vUv=uv;gl_Position=vec4(position,0.,1.);}`;
const fragment = `precision highp float;
uniform vec3 iResolution; uniform vec2 iMouse; uniform float iTime,uSpeed,uScale,uTurbulence,uFluidity,uRimWidth,uSharpness,uShimmer,uGlow,uOpacity,uMouseEnabled,uMouseStrength,uMouseRadius; uniform vec2 uFlow; uniform vec3 uColor0,uColor1,uColor2; varying vec2 vUv;
#define PI 3.14159265
float hash(vec3 p){p=fract(p*.1031);p+=dot(p,p.zyx+33.33);return fract((p.x+p.y)*p.z);} float smin(float a,float b,float k){return -k*log2(exp2(-a/k)+exp2(-b/k));} float sl(float a,float b,float w){return mix(a,b,(sin(w*PI-PI/2.)+1.)/2.);}
float vn(vec2 p,float s,float seed){vec2 c=floor(p/s),r=mod(p,s);float a=hash(vec3(c,seed)),b=hash(vec3(c.x+1.,c.y,seed)),d=hash(vec3(c.x+1.,c.y+1.,seed)),e=hash(vec3(c.x,c.y+1.,seed));return sl(sl(a,b,r.x/s),sl(e,d,r.x/s),r.y/s);}
float dbn(vec2 p,float s,float seed){float o=s/2.;return(2.*vn(p,s,seed)+1.5*vn(p+vec2(o,o),s,seed+.1)+1.25*vn(p+vec2(-o,o),s,seed+.2)+1.125*vn(p+vec2(o,-o),s,seed+.3)+vn(p+vec2(-o,-o),s,seed+.4))/7.;}
void main(){float ref=700./max(uScale,.05);vec2 p=vUv*iResolution.xy/iResolution.y*ref;float spd=200.*uSpeed,t=iTime;vec2 d=uFlow,perp=vec2(-d.y,d.x);float a=vn(p+perp*(t*spd),60.,10.)*50.*uTurbulence,b=vn(p-perp*(t*spd),120.,15.)*100.*uTurbulence;float x=dbn(p+a+d*(t*spd*.5),40.,1.),y=dbn(p+b-d*(t*spd*.5),40.,0.),m=smin(x,y,max(uFluidity,.001)),mg=0.;if(uMouseEnabled>.5){vec2 mp=iMouse/iResolution.y*ref;float md=length(p-mp)/ref,rr=max(uMouseRadius,.02);mg=exp(-md*md/(rr*rr))*uMouseStrength;}float band=(uRimWidth-abs((m-.4)*2.))*5.;float light=clamp(band-vn(p+d*(t*spd*.5),60.,12.)*uShimmer,0.,1.);light=pow(light,uSharpness)*uGlow*clamp(1.-mg,0.,1.);float h=clamp(.5+(x-y)*.8,0.,1.);vec3 color=h<.5?mix(uColor0,uColor1,h*2.):mix(uColor1,uColor2,(h-.5)*2.);vec3 outc=color*light;gl_FragColor=vec4(outc,clamp(max(outc.r,max(outc.g,outc.b)),0.,1.)*uOpacity);}`;

export default function Ferrofluid({ className, colors = ["#ffffff", "#ffffff", "#ffffff"], speed = .5, scale = 1.6, turbulence = 1, fluidity = .1, rimWidth = .2, sharpness = 2.5, shimmer = 1.5, glow = 2, flowDirection = "down", opacity = 1, mouseInteraction = true, mouseStrength = 1, mouseRadius = .35, mouseDampening = .15 }: Props) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { const node = ref.current; if (!node) return; const renderer = new Renderer({ alpha: true, antialias: true, dpr: Math.min(window.devicePixelRatio, 2) }); const gl = renderer.gl, canvas = gl.canvas as HTMLCanvasElement; gl.clearColor(0, 0, 0, 0); node.appendChild(canvas); const palette = [colors[0], colors[1] ?? colors[0], colors[2] ?? colors[0]].map(rgb);
    const uniforms = { iResolution:{value:[1,1,1]},iMouse:{value:[0,0]},iTime:{value:0},uColor0:{value:palette[0]},uColor1:{value:palette[1]},uColor2:{value:palette[2]},uFlow:{value:direction(flowDirection)},uSpeed:{value:speed},uScale:{value:scale},uTurbulence:{value:turbulence},uFluidity:{value:fluidity},uRimWidth:{value:rimWidth},uSharpness:{value:sharpness},uShimmer:{value:shimmer},uGlow:{value:glow},uOpacity:{value:opacity},uMouseEnabled:{value:mouseInteraction?1:0},uMouseStrength:{value:mouseStrength},uMouseRadius:{value:mouseRadius} };
    const mesh = new Mesh(gl,{geometry:new Triangle(gl),program:new Program(gl,{vertex,fragment,uniforms})}); const target=[0,0]; let last=0,frame=0; const resize=()=>{const r=node.getBoundingClientRect();renderer.setSize(r.width,r.height);uniforms.iResolution.value=[gl.drawingBufferWidth,gl.drawingBufferHeight,1];}; const move=(e:PointerEvent)=>{const r=canvas.getBoundingClientRect(),dpr=renderer.dpr||1;target[0]=(e.clientX-r.left)*dpr;target[1]=(r.height-(e.clientY-r.top))*dpr;}; const ro=new ResizeObserver(resize);ro.observe(node);resize();if(mouseInteraction)canvas.addEventListener("pointermove",move);const loop=(time:number)=>{frame=requestAnimationFrame(loop);uniforms.iTime.value=time*.001;const dt=last?(time-last)/1000:0;last=time;const f=mouseDampening>0?1-Math.exp(-dt/Math.max(.0001,mouseDampening)):1;const cur=uniforms.iMouse.value as number[];cur[0]+=(target[0]-cur[0])*f;cur[1]+=(target[1]-cur[1])*f;renderer.render({scene:mesh});};frame=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(frame);ro.disconnect();canvas.removeEventListener("pointermove",move);canvas.remove();}; },[colors,speed,scale,turbulence,fluidity,rimWidth,sharpness,shimmer,glow,flowDirection,opacity,mouseInteraction,mouseStrength,mouseRadius,mouseDampening]);
  return <div ref={ref} aria-hidden="true" className={`ferrofluid-container ${className ?? ""}`} />;
}
